name: binary_declarations
version: 0.0.49
author: Andrew Mezoni <andrew.mezoni@gmail.com>
description: Binary declarations is a set of classes for parsing declarations of the binary types specified in textual form.
homepage: https://github.com/mezoni/binary_declarations
dependencies:
  build_tools: any
  macro_processor: any
  parser_error: any
  path: any
  text: any
dev_dependencies:
  unittest: any
